import { Home as RealHome } from './Home';
import { Teams as RealTeams } from './Teams';
import { TeamProfile as RealTeamProfile } from './TeamProfile';
import { Players as RealPlayers } from './Players';
import { PlayerProfile as RealPlayerProfile } from './PlayerProfile';
import { Matches as RealMatches } from './Matches';
import { LiveScores as RealLiveScores } from './LiveScores';
import { PointsTable as RealPointsTable } from './PointsTable';
import { Stats as RealStats } from './Stats';
import { Sponsors as RealSponsors } from './Sponsors';
import { Gallery as RealGallery } from './Gallery';
import { Videos as RealVideos } from './Videos';
import { News as RealNews } from './News';
import { About as RealAbout } from './About';
import { Contact as RealContact } from './Contact';
import { Admin as RealAdmin } from './Admin';

export const Home = RealHome;
export const Teams = RealTeams;
export const TeamProfile = RealTeamProfile;
export const Players = RealPlayers;
export const PlayerProfile = RealPlayerProfile;
export const Matches = RealMatches;
export const LiveScores = RealLiveScores;
export const PointsTable = RealPointsTable;
export const Stats = RealStats;
export const Sponsors = RealSponsors;
export const Gallery = RealGallery;
export const Videos = RealVideos;
export const News = RealNews;
export const About = RealAbout;
export const Contact = RealContact;
export const Admin = RealAdmin;